name: Build ZMK Firmware (Central + 2 Peripherals)

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board1: nice_nano_v2
      shield1: corne_central
      board2: nice_nano_v2
      shield2: corne_left
      board3: nice_nano_v2
      shield3: corne_right
      keymap: default
    secrets: inherit

  artifact-management:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: zmk-*.uf2
          merge-multiple: true

      - name: Organize firmware
        run: |
          mkdir -p firmware
          mv artifacts/corne_central-nice_nano_v2-zmk.uf2 firmware/central.uf2
          mv artifacts/corne_left-nice_nano_v2-zmk.uf2 firmware/left.uf2
          mv artifacts/corne_right-nice_nano_v2-zmk.uf2 firmware/right.uf2
          ls -la firmware/

      - name: Upload final artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: firmware/*
          if-no-files-found: error
