name: Build ZMK Firmware (Central + 2 Peripherals)

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: nice_nano_v2
      shield: |
        corne_central
        corne_left
        corne_right
      keymap: default
    secrets: inherit

  artifact-management:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Rename and organize artifacts
        run: |
          mkdir -p firmware
          # Central
          cp artifacts/corne_central-nice_nano_v2-zmk.uf2 firmware/central.uf2
          # Left
          cp artifacts/corne_left-nice_nano_v2-zmk.uf2 firmware/left.uf2
          # Right
          cp artifacts/corne_right-nice_nano_v2-zmk.uf2 firmware/right.uf2

      - name: Upload combined firmware
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware-bundle
          path: firmware/
          compression-level: 0
