name: Build ZMK Firmware (3-part Split)

on: [push, pull_request, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: zmk

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          git cmake ninja-build gcc g++ \
          device-tree-compiler dfu-util \
          libncurses-dev libssl-dev

      - name: Install West
        run: |
          python -m pip install --upgrade pip
          pip install west
          west --version

  build-left:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: zmk

      - name: Initialize Zephyr
        run: |
          cd zmk
          west init -l app
          west update
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Build Left
        run: |
          cd zmk
          west build -b nice_nano_v2 --pristine -- -DSHIELD=corne_left -DZMK_CONFIG="$GITHUB_WORKSPACE/config"
          mkdir -p ../firmware
          cp build/zephyr/zmk.uf2 ../firmware/left.uf2

      - uses: actions/upload-artifact@v4
        with:
          name: left-firmware
          path: firmware/left.uf2

  build-central:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: zmk

      - name: Initialize Zephyr
        run: |
          cd zmk
          west init -l app
          west update
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Build Central
        run: |
          cd zmk
          west build -b nice_nano_v2 --pristine -- -DSHIELD=corne_central -DZMK_CONFIG="$GITHUB_WORKSPACE/config"
          mkdir -p ../firmware
          cp build/zephyr/zmk.uf2 ../firmware/central.uf2

      - uses: actions/upload-artifact@v4
        with:
          name: central-firmware
          path: firmware/central.uf2

  build-right:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: zmk

      - name: Initialize Zephyr
        run: |
          cd zmk
          west init -l app
          west update
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Build Right
        run: |
          cd zmk
          west build -b nice_nano_v2 --pristine -- -DSHIELD=corne_right -DZMK_CONFIG="$GITHUB_WORKSPACE/config"
          mkdir -p ../firmware
          cp build/zephyr/zmk.uf2 ../firmware/right.uf2

      - uses: actions/upload-artifact@v4
        with:
          name: right-firmware
          path: firmware/right.uf2

  combine:
    needs: [build-left, build-central, build-right]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Combine firmware
        run: |
          mkdir -p combined
          cp artifacts/left-firmware/left.uf2 combined/
          cp artifacts/central-firmware/central.uf2 combined/
          cp artifacts/right-firmware/right.uf2 combined/
          ls -lh combined/

      - uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware-bundle
          path: combined/*.uf2
